### PR TITLE
Revert "fixed typo in readme"

### PR DESCRIPTION
**Pull request by emre**
Reverts emre/lama#9

@f izin vermiyor.

### CODE REVIEW

**Comment by samed** [comment]
:+1:

**Comment by f** [comment]
It's revert of https://github.com/emre/lama/pull/9, "readme typo fix bu deYil".

**Comment by emre** [comment]
thanks for the explanation @f, topic/description of the PR is not clear enough to indicate that is a revert of #9.

**Comment by samed** [comment]
@emre  :+1:

**Comment by berkerpeksag** [comment]
> thanks for the explanation @f, topic of the PR is not clear enough to indicate that is a revert of #9.

VALID

**Comment by f** [comment]
@berkerpeksag Public validations (like GH comments) are not legal in http://github.com/pyistanbul/validation-rules

**Comment by ogta** [comment]
@f and @emre thank you for show me my mistake :smiley: and @f link is give me 404

**Pull request merged**
